"""card-on-file stored_card + card_charge

Revision ID: 28c686247d41
Revises: cdecca6a35e4
Create Date: 2026-07-12 16:22:12.656371
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# The shared `brand` enum already exists (created by the initial migration). Reference it
# WITHOUT re-creating the type (create_type=False) — standing gotcha, PROGRESS.md §5.
brand_enum = postgresql.ENUM('victoria', 'nanaimo', name='brand', create_type=False)


# revision identifiers, used by Alembic.
revision: str = '28c686247d41'
down_revision: Union[str, None] = 'cdecca6a35e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_card',
    sa.Column('residential_customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=180), nullable=True),
    sa.Column('square_customer_id', sa.String(length=64), nullable=False),
    sa.Column('square_card_id', sa.String(length=80), nullable=False),
    sa.Column('card_brand', sa.String(length=24), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('authorized_by', sa.String(length=120), nullable=True),
    sa.Column('auth_note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.ForeignKeyConstraint(['residential_customer_id'], ['residential_customer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stored_card_brand'), 'stored_card', ['brand'], unique=False)
    op.create_index(op.f('ix_stored_card_customer_name'), 'stored_card', ['customer_name'], unique=False)
    op.create_index(op.f('ix_stored_card_residential_customer_id'), 'stored_card', ['residential_customer_id'], unique=False)
    op.create_table('card_charge',
    sa.Column('stored_card_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('square_payment_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stored_card_id'], ['stored_card.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_charge_brand'), 'card_charge', ['brand'], unique=False)
    op.create_index(op.f('ix_card_charge_job_id'), 'card_charge', ['job_id'], unique=False)
    op.create_index(op.f('ix_card_charge_stored_card_id'), 'card_charge', ['stored_card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_charge_stored_card_id'), table_name='card_charge')
    op.drop_index(op.f('ix_card_charge_job_id'), table_name='card_charge')
    op.drop_index(op.f('ix_card_charge_brand'), table_name='card_charge')
    op.drop_table('card_charge')
    op.drop_index(op.f('ix_stored_card_residential_customer_id'), table_name='stored_card')
    op.drop_index(op.f('ix_stored_card_customer_name'), table_name='stored_card')
    op.drop_index(op.f('ix_stored_card_brand'), table_name='stored_card')
    op.drop_table('stored_card')
    # ### end Alembic commands ###
