"""bin-tracker driver day, field weights, tool daily log

Revision ID: 44049978642e
Revises: d83e4b664737
Create Date: 2026-07-10 08:33:55.559681
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44049978642e'
down_revision: Union[str, None] = 'd83e4b664737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The `brand` enum already exists (shared across every table) — reference it, never
# re-CREATE it (create_type=False), per the Alembic gotcha in PROGRESS.md.
brand_enum = postgresql.ENUM('victoria', 'nanaimo', name='brand', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_driver_day',
    sa.Column('driver', sa.String(length=120), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('truck', sa.String(length=60), nullable=True),
    sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'driver', 'work_date', name='uq_binday_brand_driver_date')
    )
    op.create_index(op.f('ix_bin_driver_day_brand'), 'bin_driver_day', ['brand'], unique=False)
    op.create_table('bin_weigh',
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('k', sa.String(length=60), nullable=False),
    sa.Column('rec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'kind', 'k', name='uq_binweigh_brand_kind_k')
    )
    op.create_index(op.f('ix_bin_weigh_brand'), 'bin_weigh', ['brand'], unique=False)
    op.create_table('tool_daily_log',
    sa.Column('truck', sa.String(length=60), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('who', sa.String(length=120), nullable=True),
    sa.Column('logged_when', sa.String(length=20), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'truck', 'log_date', name='uq_tooldaily_brand_truck_date')
    )
    op.create_index(op.f('ix_tool_daily_log_brand'), 'tool_daily_log', ['brand'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_daily_log_brand'), table_name='tool_daily_log')
    op.drop_table('tool_daily_log')
    op.drop_index(op.f('ix_bin_weigh_brand'), table_name='bin_weigh')
    op.drop_table('bin_weigh')
    op.drop_index(op.f('ix_bin_driver_day_brand'), table_name='bin_driver_day')
    op.drop_table('bin_driver_day')
    # ### end Alembic commands ###
