"""yard_processing

Revision ID: 4cd57b8ea105
Revises: f07d84908f04
Create Date: 2026-07-09 19:52:07.127341
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd57b8ea105'
down_revision: Union[str, None] = 'f07d84908f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# `brand` already exists -> reference it (create_type=False, don't re-create).
brand = postgresql.ENUM('victoria', 'nanaimo', name='brand', create_type=False)


def upgrade() -> None:
    op.create_table('yard_processing',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('ref', sa.String(length=60), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('roofing', sa.Boolean(), nullable=False),
    sa.Column('customer', sa.String(length=180), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('town', sa.String(length=120), nullable=True),
    sa.Column('pickup_by', sa.String(length=120), nullable=True),
    sa.Column('truck', sa.String(length=60), nullable=True),
    sa.Column('hq_time', sa.String(length=20), nullable=True),
    sa.Column('pick_date', sa.String(length=20), nullable=True),
    sa.Column('crew', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crew_count', sa.Integer(), nullable=True),
    sa.Column('gross_f', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_r', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tare_f', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tare_r', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('waste_class', sa.String(length=120), nullable=True),
    sa.Column('dump_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pct', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('process_notes', sa.Text(), nullable=True),
    sa.Column('sort_minutes', sa.Integer(), nullable=True),
    sa.Column('weighed', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_clock', sa.String(length=20), nullable=True),
    sa.Column('processed_date', sa.Date(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'code', 'processed_date', name='uq_yardproc_brand_code_date')
    )
    op.create_index(op.f('ix_yard_processing_brand'), 'yard_processing', ['brand'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yard_processing_brand'), table_name='yard_processing')
    op.drop_table('yard_processing')
    # ### end Alembic commands ###
