"""po chase table

Revision ID: 56b3b57eb7b6
Revises: a5abfdbdebfc
Create Date: 2026-07-10 12:49:35.552138
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56b3b57eb7b6'
down_revision: Union[str, None] = 'a5abfdbdebfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reference the shared `brand` enum, never re-CREATE it (PROGRESS.md gotcha).
brand_enum = postgresql.ENUM('victoria', 'nanaimo', name='brand', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('po_chase',
    sa.Column('source_id', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'source_id', name='uq_po_brand_source')
    )
    op.create_index(op.f('ix_po_chase_brand'), 'po_chase', ['brand'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_po_chase_brand'), table_name='po_chase')
    op.drop_table('po_chase')
    # ### end Alembic commands ###
