"""hands-on truck pre-check log

Revision ID: 70f23a968aa0
Revises: e7b266ed5ed6
Create Date: 2026-07-10 09:45:36.068728
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70f23a968aa0'
down_revision: Union[str, None] = 'e7b266ed5ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reference the shared `brand` enum, never re-CREATE it (PROGRESS.md gotcha).
brand_enum = postgresql.ENUM('victoria', 'nanaimo', name='brand', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precheck_log',
    sa.Column('truck', sa.String(length=60), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('who', sa.String(length=120), nullable=True),
    sa.Column('logged_when', sa.String(length=20), nullable=True),
    sa.Column('flagged', sa.Integer(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'truck', 'check_date', name='uq_precheck_brand_truck_date')
    )
    op.create_index(op.f('ix_precheck_log_brand'), 'precheck_log', ['brand'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_precheck_log_brand'), table_name='precheck_log')
    op.drop_table('precheck_log')
    # ### end Alembic commands ###
