"""day-board overlays, attendance, breaks, day notes, brand settings

Revision ID: 84b98fe168ce
Revises: 44049978642e
Create Date: 2026-07-10 09:09:50.089462
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84b98fe168ce'
down_revision: Union[str, None] = '44049978642e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reference the shared `brand` enum, never re-CREATE it (PROGRESS.md gotcha).
brand_enum = postgresql.ENUM('victoria', 'nanaimo', name='brand', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('employee_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('late_time', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'work_date', 'employee_name', name='uq_attendance_brand_date_name')
    )
    op.create_index(op.f('ix_attendance_brand'), 'attendance', ['brand'], unique=False)
    op.create_table('brand_setting',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'key', name='uq_setting_brand_key')
    )
    op.create_index(op.f('ix_brand_setting_brand'), 'brand_setting', ['brand'], unique=False)
    op.create_table('break_log',
    sa.Column('employee_name', sa.String(length=120), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=True),
    sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'employee_name', 'work_date', name='uq_break_brand_name_date')
    )
    op.create_index(op.f('ix_break_log_brand'), 'break_log', ['brand'], unique=False)
    op.create_table('day_note',
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('bin', sa.Text(), nullable=True),
    sa.Column('yard', sa.Text(), nullable=True),
    sa.Column('handson', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'note_date', name='uq_daynote_brand_date')
    )
    op.create_index(op.f('ix_day_note_brand'), 'day_note', ['brand'], unique=False)
    op.create_table('dayboard_overlay',
    sa.Column('event_id', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sitelog', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'event_id', name='uq_dayboard_brand_event')
    )
    op.create_index(op.f('ix_dayboard_overlay_brand'), 'dayboard_overlay', ['brand'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dayboard_overlay_brand'), table_name='dayboard_overlay')
    op.drop_table('dayboard_overlay')
    op.drop_index(op.f('ix_day_note_brand'), table_name='day_note')
    op.drop_table('day_note')
    op.drop_index(op.f('ix_break_log_brand'), table_name='break_log')
    op.drop_table('break_log')
    op.drop_index(op.f('ix_brand_setting_brand'), table_name='brand_setting')
    op.drop_table('brand_setting')
    op.drop_index(op.f('ix_attendance_brand'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
