"""clock punch gcal_event_id for punch-calendar mirror

Revision ID: a5abfdbdebfc
Revises: 70f23a968aa0
Create Date: 2026-07-10 10:54:12.705794
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5abfdbdebfc'
down_revision: Union[str, None] = '70f23a968aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clock_punch', sa.Column('gcal_event_id', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clock_punch', 'gcal_event_id')
    # ### end Alembic commands ###
