"""followup review phone/account/sent tracking

Revision ID: cdecca6a35e4
Revises: f209105d0be8
Create Date: 2026-07-12 09:02:48.927752
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdecca6a35e4'
down_revision: Union[str, None] = 'f209105d0be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followup_review', sa.Column('account', sa.String(length=30), nullable=True))
    op.add_column('followup_review', sa.Column('phone', sa.String(length=40), nullable=True))
    op.add_column('followup_review', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('followup_review', sa.Column('sent_to', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followup_review', 'sent_to')
    op.drop_column('followup_review', 'sent_at')
    op.drop_column('followup_review', 'phone')
    op.drop_column('followup_review', 'account')
    # ### end Alembic commands ###
