"""followup reviews + consumables usage ledger

Revision ID: e7b266ed5ed6
Revises: 84b98fe168ce
Create Date: 2026-07-10 09:37:55.489844
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7b266ed5ed6'
down_revision: Union[str, None] = '84b98fe168ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reference the shared `brand` enum, never re-CREATE it (PROGRESS.md gotcha).
brand_enum = postgresql.ENUM('victoria', 'nanaimo', name='brand', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followup_review',
    sa.Column('source_id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('review_sent', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'source_id', name='uq_review_brand_source')
    )
    op.create_index(op.f('ix_followup_review_brand'), 'followup_review', ['brand'], unique=False)
    op.create_table('usage_event',
    sa.Column('item_id', sa.String(length=60), nullable=True),
    sa.Column('item_name', sa.String(length=180), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('at_iso', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand_enum, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'item_id', 'at_iso', 'type', name='uq_usage_brand_item_at_type')
    )
    op.create_index(op.f('ix_usage_event_brand'), 'usage_event', ['brand'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_event_brand'), table_name='usage_event')
    op.drop_table('usage_event')
    op.drop_index(op.f('ix_followup_review_brand'), table_name='followup_review')
    op.drop_table('followup_review')
    # ### end Alembic commands ###
