"""field_job and weigh_log

Revision ID: f07d84908f04
Revises: f9deb88289a1
Create Date: 2026-07-09 19:45:39.839223
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f07d84908f04'
down_revision: Union[str, None] = 'f9deb88289a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# `brand` already exists -> reference it (create_type=False, don't re-create).
brand = postgresql.ENUM('victoria', 'nanaimo', name='brand', create_type=False)


def upgrade() -> None:
    op.create_table('field_job',
    sa.Column('source_id', sa.String(length=60), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('customer', sa.String(length=180), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('visits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'source_id', name='uq_field_job_brand_source')
    )
    op.create_index(op.f('ix_field_job_brand'), 'field_job', ['brand'], unique=False)
    op.create_table('weigh_log',
    sa.Column('source_at', sa.BigInteger(), nullable=True),
    sa.Column('weigh_date', sa.Date(), nullable=True),
    sa.Column('weigh_time', sa.String(length=20), nullable=True),
    sa.Column('who', sa.String(length=120), nullable=True),
    sa.Column('truck', sa.String(length=60), nullable=True),
    sa.Column('bin', sa.String(length=20), nullable=True),
    sa.Column('cls', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('front_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rear_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'source_at', 'bin', name='uq_weigh_brand_at_bin')
    )
    op.create_index(op.f('ix_weigh_log_brand'), 'weigh_log', ['brand'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weigh_log_brand'), table_name='weigh_log')
    op.drop_table('weigh_log')
    op.drop_index(op.f('ix_field_job_brand'), table_name='field_job')
    op.drop_table('field_job')
    # ### end Alembic commands ###
