"""sms opt-out + message log

Revision ID: f209105d0be8
Revises: 56b3b57eb7b6
Create Date: 2026-07-10 13:04:46.181615
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f209105d0be8'
down_revision: Union[str, None] = '56b3b57eb7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reference the shared `brand` enum, never re-CREATE it (PROGRESS.md gotcha).
brand_enum = postgresql.ENUM('victoria', 'nanaimo', name='brand', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_message',
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('brand', brand_enum, nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('twilio_sid', sa.String(length=64), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_message_brand'), 'sms_message', ['brand'], unique=False)
    op.create_table('sms_opt_out',
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms_opt_out')
    op.drop_index(op.f('ix_sms_message_brand'), table_name='sms_message')
    op.drop_table('sms_message')
    # ### end Alembic commands ###
