"""incidents and clock

Revision ID: f9deb88289a1
Revises: 7e6386222973
Create Date: 2026-07-09 19:36:07.726958
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9deb88289a1'
down_revision: Union[str, None] = '7e6386222973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# `brand` already exists -> reference it (create_type=False, don't re-create).
brand = postgresql.ENUM('victoria', 'nanaimo', name='brand', create_type=False)


def upgrade() -> None:
    op.create_table('clock_punch',
    sa.Column('employee_name', sa.String(length=120), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('in_time', sa.String(length=20), nullable=True),
    sa.Column('out_time', sa.String(length=20), nullable=True),
    sa.Column('done_time', sa.String(length=20), nullable=True),
    sa.Column('truck', sa.String(length=60), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'employee_name', 'work_date', name='uq_clock_brand_name_date')
    )
    op.create_index(op.f('ix_clock_punch_brand'), 'clock_punch', ['brand'], unique=False)
    op.create_table('incident',
    sa.Column('source_id', sa.String(length=60), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('sev', sa.String(length=40), nullable=True),
    sa.Column('told', sa.String(length=60), nullable=True),
    sa.Column('reported_by', sa.String(length=120), nullable=True),
    sa.Column('who', sa.String(length=255), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('incident_time', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('truck', sa.String(length=60), nullable=True),
    sa.Column('what', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('brand', brand, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'source_id', name='uq_incident_brand_source')
    )
    op.create_index(op.f('ix_incident_brand'), 'incident', ['brand'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_brand'), table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_clock_punch_brand'), table_name='clock_punch')
    op.drop_table('clock_punch')
    # ### end Alembic commands ###
